### ISSUE TITLE
Questions about the code

### ISSUE THREAD

**Issue by HuangLuchen** [Shadab442/dqn-leo-handover-python#7]
in leo_parameters, we have
def calculate_leo_parameters(self):
        for i,leo in enumerate(self.leos [0:100]):
The number of starlink is more than 100. Why this sentence circulate only 100 satellites? What about others?
     Thank you a lot!

**Comment by Shadab442** [comment]
I just took the first 100 satellites, you can consider more if you need to. In the TLE file that I provided in this repository, I have the TLE information of 3980 satellites, so that is the maximum number of satellites you can consider if you use that TLE file.

**Comment by HuangLuchen** [comment]
Thank you! That's help me a lot

**Comment by Shadab442** [comment]
Glad to be able to help you!!
